# BuildNumber is injected at build time; run "make build" or "make" to include version.
BUILD_VER := $(shell (cat VERSION 2>/dev/null || git describe --tags --always 2>/dev/null || echo dev) | tr -d '\n')

# Demo DB lives in project root only; safe to delete with clean (never touches user's ~/.local/share/vibe/vibe.db)
DEMO_DB := $(CURDIR)/vibe-demo.db

# Include config.mk from configure; fallback if not run
-include config.mk
GO ?= $(shell (command -v /usr/local/go/bin/go >/dev/null 2>&1 && echo /usr/local/go/bin/go) || echo go)

# Package name for build-package (e.g. vibePDA-0.7.0)
PKG_NAME := vibePDA-$(BUILD_VER)
PKG_DIR := $(CURDIR)/dist/$(PKG_NAME)

# Markdown docs and their ASCII .txt equivalents (generated by docs-txt)
MD_DOCS := README.md CHANGELOG.md PLAN.md docs/TESTING.md demo/README.md

.PHONY: build all clean test check check-go build-demo build-package docs-txt
all: build-package

check-go:
	@ver=$$($(GO) version 2>/dev/null | sed -n 's/.*go\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p'); \
	major=$$(echo "$$ver" | cut -d. -f1); minor=$$(echo "$$ver" | cut -d. -f2); patch=$$(echo "$$ver" | cut -d. -f3); \
	need_major=1; need_minor=24; need_patch=2; \
	if [ -z "$$ver" ]; then echo "ERROR: go not found. Run: ./scripts/install-go.sh"; exit 1; fi; \
	if [ "$$major" -lt $$need_major ] || { [ "$$major" -eq $$need_major ] && [ "$$minor" -lt $$need_minor ]; }; then \
		echo "ERROR: Go 1.24.2+ required (found: $$ver). Run: ./scripts/install-go.sh"; exit 1; fi; \
	if [ "$$minor" -eq $$need_minor ] && [ -n "$$patch" ] && [ "$$patch" -lt $$need_patch ]; then \
		echo "ERROR: Go 1.24.2+ required (found: $$ver). Run: ./scripts/install-go.sh"; exit 1; fi

build: check-go
	$(GO) build -ldflags "-X github.com/you/vibe/internal/app.BuildNumber=$(BUILD_VER)" -o vibePDA ./cmd/vibe

# build-demo: build and seed demo db with 100+ records per module (data from demo/ dir)
build-demo: check-go
	$(GO) build -ldflags "-X github.com/you/vibe/internal/app.BuildNumber=$(BUILD_VER)" -o vibePDA ./cmd/vibe
	$(GO) run ./cmd/vibe-seed -db=$(DEMO_DB)
	@echo "Demo ready. Run: VIBE_DB=$(DEMO_DB) ./vibePDA"

# docs-txt: generate .txt ASCII equivalent for each .md (no pandoc required)
docs-txt: check-go
	@$(GO) run scripts/md2txt.go $(MD_DOCS)
	@echo "Generated .txt for all markdown docs"

# build-package: produce redistributable tar.gz with binary and documentation
build-package: check-go build docs-txt
	@rm -rf "$(PKG_DIR)" "$(CURDIR)/dist/$(PKG_NAME).tar.gz"
	@mkdir -p "$(PKG_DIR)"
	@cp vibePDA "$(PKG_DIR)/"
	@cp README.md CHANGELOG.md PLAN.md README.txt CHANGELOG.txt PLAN.txt "$(PKG_DIR)/"
	@echo "vibePDA $(BUILD_VER) - https://github.com/you/vibe" > "$(PKG_DIR)/VERSION"
	@[ -d docs ] && cp -r docs "$(PKG_DIR)/" || true
	@mkdir -p "$(PKG_DIR)/demo" && cp demo/README.md demo/README.txt "$(PKG_DIR)/demo/" 2>/dev/null || true
	@(cd dist && tar czf "$(PKG_NAME).tar.gz" "$(PKG_NAME)")
	@rm -rf "$(PKG_DIR)"
	@echo "Created dist/$(PKG_NAME).tar.gz"

clean:
	rm -f vibe vibePDA
	rm -rf dist
	@# Only remove demo db if it is exactly our known path (never touch user's real db)
	@if [ -f "$(DEMO_DB)" ]; then rm -f "$(DEMO_DB)"; echo "removed demo db $(DEMO_DB)"; fi

test: check-go
	$(GO) test ./...

check: check-go
	$(GO) test ./...
